# Generated by Django 3.0.6 on 2020-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
