# Generated by Django 3.0.6 on 2020-08-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_station_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='Slogan',
            field=models.CharField(default='', max_length=50),
        ),
    ]
