# Generated by Django 3.0.6 on 2020-08-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_station_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='desc',
            field=models.CharField(max_length=1000),
        ),
    ]
